# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
  labels:
    app: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: bookcatalog:1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://lib_admin:aNhdWIFLutFyc5Y2DruYoNzq9GoIntMo@dpg-cs2ckvm8ii6s739fi570-a.oregon-postgres.render.com/lib_db_gdi5"
        - name: ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000
